// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	k8s "github.com/flyteorg/flytepropeller/pkg/compiler/transformers/k8s"
	mock "github.com/stretchr/testify/mock"

	storage "github.com/flyteorg/flytestdlib/storage"
)

// WfClosureCrdFieldsStore is an autogenerated mock type for the WfClosureCrdFieldsStore type
type WfClosureCrdFieldsStore struct {
	mock.Mock
}

type WfClosureCrdFieldsStore_Get struct {
	*mock.Call
}

func (_m WfClosureCrdFieldsStore_Get) Return(_a0 *k8s.WfClosureCrdFields, _a1 error) *WfClosureCrdFieldsStore_Get {
	return &WfClosureCrdFieldsStore_Get{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *WfClosureCrdFieldsStore) OnGet(ctx context.Context, dataReference storage.DataReference) *WfClosureCrdFieldsStore_Get {
	c_call := _m.On("Get", ctx, dataReference)
	return &WfClosureCrdFieldsStore_Get{Call: c_call}
}

func (_m *WfClosureCrdFieldsStore) OnGetMatch(matchers ...interface{}) *WfClosureCrdFieldsStore_Get {
	c_call := _m.On("Get", matchers...)
	return &WfClosureCrdFieldsStore_Get{Call: c_call}
}

// Get provides a mock function with given fields: ctx, dataReference
func (_m *WfClosureCrdFieldsStore) Get(ctx context.Context, dataReference storage.DataReference) (*k8s.WfClosureCrdFields, error) {
	ret := _m.Called(ctx, dataReference)

	var r0 *k8s.WfClosureCrdFields
	if rf, ok := ret.Get(0).(func(context.Context, storage.DataReference) *k8s.WfClosureCrdFields); ok {
		r0 = rf(ctx, dataReference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*k8s.WfClosureCrdFields)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, storage.DataReference) error); ok {
		r1 = rf(ctx, dataReference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type WfClosureCrdFieldsStore_Remove struct {
	*mock.Call
}

func (_m WfClosureCrdFieldsStore_Remove) Return(_a0 error) *WfClosureCrdFieldsStore_Remove {
	return &WfClosureCrdFieldsStore_Remove{Call: _m.Call.Return(_a0)}
}

func (_m *WfClosureCrdFieldsStore) OnRemove(ctx context.Context, dataReference storage.DataReference) *WfClosureCrdFieldsStore_Remove {
	c_call := _m.On("Remove", ctx, dataReference)
	return &WfClosureCrdFieldsStore_Remove{Call: c_call}
}

func (_m *WfClosureCrdFieldsStore) OnRemoveMatch(matchers ...interface{}) *WfClosureCrdFieldsStore_Remove {
	c_call := _m.On("Remove", matchers...)
	return &WfClosureCrdFieldsStore_Remove{Call: c_call}
}

// Remove provides a mock function with given fields: ctx, dataReference
func (_m *WfClosureCrdFieldsStore) Remove(ctx context.Context, dataReference storage.DataReference) error {
	ret := _m.Called(ctx, dataReference)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.DataReference) error); ok {
		r0 = rf(ctx, dataReference)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
