# This is a sample configuration file.
# Real configuration when running inside K8s (local or otherwise) lives in a ConfigMap
storage:
  connection:
    endpoint: "./_test"
  type: local
  container: "bucket"
logger:
  level: 4
  show-source: true
