apiVersion: v1
data:
  config.yaml: |
    storage:
      connection:
        access-key: minio
        auth-type: accesskey
        disable-ssl: true
        endpoint: http://minio.flyte.svc.cluster.local:9000
        region: us-east-1
        secret-key: miniostorage
      type: minio
      container: "my-s3-bucket"
kind: ConfigMap
metadata:
  annotations:
  name: flyte-data-config
  namespace: default
