// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/flyteorg/flyteplugins/go/tasks/pluginmachinery/catalog"

	handler "github.com/flyteorg/flytepropeller/pkg/controller/nodes/handler"

	mock "github.com/stretchr/testify/mock"
)

// CacheableNode is an autogenerated mock type for the CacheableNode type
type CacheableNode struct {
	mock.Mock
}

type CacheableNode_Abort struct {
	*mock.Call
}

func (_m CacheableNode_Abort) Return(_a0 error) *CacheableNode_Abort {
	return &CacheableNode_Abort{Call: _m.Call.Return(_a0)}
}

func (_m *CacheableNode) OnAbort(ctx context.Context, executionContext handler.NodeExecutionContext, reason string) *CacheableNode_Abort {
	c_call := _m.On("Abort", ctx, executionContext, reason)
	return &CacheableNode_Abort{Call: c_call}
}

func (_m *CacheableNode) OnAbortMatch(matchers ...interface{}) *CacheableNode_Abort {
	c_call := _m.On("Abort", matchers...)
	return &CacheableNode_Abort{Call: c_call}
}

// Abort provides a mock function with given fields: ctx, executionContext, reason
func (_m *CacheableNode) Abort(ctx context.Context, executionContext handler.NodeExecutionContext, reason string) error {
	ret := _m.Called(ctx, executionContext, reason)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, handler.NodeExecutionContext, string) error); ok {
		r0 = rf(ctx, executionContext, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type CacheableNode_Finalize struct {
	*mock.Call
}

func (_m CacheableNode_Finalize) Return(_a0 error) *CacheableNode_Finalize {
	return &CacheableNode_Finalize{Call: _m.Call.Return(_a0)}
}

func (_m *CacheableNode) OnFinalize(ctx context.Context, executionContext handler.NodeExecutionContext) *CacheableNode_Finalize {
	c_call := _m.On("Finalize", ctx, executionContext)
	return &CacheableNode_Finalize{Call: c_call}
}

func (_m *CacheableNode) OnFinalizeMatch(matchers ...interface{}) *CacheableNode_Finalize {
	c_call := _m.On("Finalize", matchers...)
	return &CacheableNode_Finalize{Call: c_call}
}

// Finalize provides a mock function with given fields: ctx, executionContext
func (_m *CacheableNode) Finalize(ctx context.Context, executionContext handler.NodeExecutionContext) error {
	ret := _m.Called(ctx, executionContext)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, handler.NodeExecutionContext) error); ok {
		r0 = rf(ctx, executionContext)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type CacheableNode_FinalizeRequired struct {
	*mock.Call
}

func (_m CacheableNode_FinalizeRequired) Return(_a0 bool) *CacheableNode_FinalizeRequired {
	return &CacheableNode_FinalizeRequired{Call: _m.Call.Return(_a0)}
}

func (_m *CacheableNode) OnFinalizeRequired() *CacheableNode_FinalizeRequired {
	c_call := _m.On("FinalizeRequired")
	return &CacheableNode_FinalizeRequired{Call: c_call}
}

func (_m *CacheableNode) OnFinalizeRequiredMatch(matchers ...interface{}) *CacheableNode_FinalizeRequired {
	c_call := _m.On("FinalizeRequired", matchers...)
	return &CacheableNode_FinalizeRequired{Call: c_call}
}

// FinalizeRequired provides a mock function with given fields:
func (_m *CacheableNode) FinalizeRequired() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type CacheableNode_GetCatalogKey struct {
	*mock.Call
}

func (_m CacheableNode_GetCatalogKey) Return(_a0 catalog.Key, _a1 error) *CacheableNode_GetCatalogKey {
	return &CacheableNode_GetCatalogKey{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *CacheableNode) OnGetCatalogKey(ctx context.Context, executionContext handler.NodeExecutionContext) *CacheableNode_GetCatalogKey {
	c_call := _m.On("GetCatalogKey", ctx, executionContext)
	return &CacheableNode_GetCatalogKey{Call: c_call}
}

func (_m *CacheableNode) OnGetCatalogKeyMatch(matchers ...interface{}) *CacheableNode_GetCatalogKey {
	c_call := _m.On("GetCatalogKey", matchers...)
	return &CacheableNode_GetCatalogKey{Call: c_call}
}

// GetCatalogKey provides a mock function with given fields: ctx, executionContext
func (_m *CacheableNode) GetCatalogKey(ctx context.Context, executionContext handler.NodeExecutionContext) (catalog.Key, error) {
	ret := _m.Called(ctx, executionContext)

	var r0 catalog.Key
	if rf, ok := ret.Get(0).(func(context.Context, handler.NodeExecutionContext) catalog.Key); ok {
		r0 = rf(ctx, executionContext)
	} else {
		r0 = ret.Get(0).(catalog.Key)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, handler.NodeExecutionContext) error); ok {
		r1 = rf(ctx, executionContext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type CacheableNode_Handle struct {
	*mock.Call
}

func (_m CacheableNode_Handle) Return(_a0 handler.Transition, _a1 error) *CacheableNode_Handle {
	return &CacheableNode_Handle{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *CacheableNode) OnHandle(ctx context.Context, executionContext handler.NodeExecutionContext) *CacheableNode_Handle {
	c_call := _m.On("Handle", ctx, executionContext)
	return &CacheableNode_Handle{Call: c_call}
}

func (_m *CacheableNode) OnHandleMatch(matchers ...interface{}) *CacheableNode_Handle {
	c_call := _m.On("Handle", matchers...)
	return &CacheableNode_Handle{Call: c_call}
}

// Handle provides a mock function with given fields: ctx, executionContext
func (_m *CacheableNode) Handle(ctx context.Context, executionContext handler.NodeExecutionContext) (handler.Transition, error) {
	ret := _m.Called(ctx, executionContext)

	var r0 handler.Transition
	if rf, ok := ret.Get(0).(func(context.Context, handler.NodeExecutionContext) handler.Transition); ok {
		r0 = rf(ctx, executionContext)
	} else {
		r0 = ret.Get(0).(handler.Transition)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, handler.NodeExecutionContext) error); ok {
		r1 = rf(ctx, executionContext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type CacheableNode_IsCacheable struct {
	*mock.Call
}

func (_m CacheableNode_IsCacheable) Return(_a0 bool, _a1 bool, _a2 error) *CacheableNode_IsCacheable {
	return &CacheableNode_IsCacheable{Call: _m.Call.Return(_a0, _a1, _a2)}
}

func (_m *CacheableNode) OnIsCacheable(ctx context.Context, executionContext handler.NodeExecutionContext) *CacheableNode_IsCacheable {
	c_call := _m.On("IsCacheable", ctx, executionContext)
	return &CacheableNode_IsCacheable{Call: c_call}
}

func (_m *CacheableNode) OnIsCacheableMatch(matchers ...interface{}) *CacheableNode_IsCacheable {
	c_call := _m.On("IsCacheable", matchers...)
	return &CacheableNode_IsCacheable{Call: c_call}
}

// IsCacheable provides a mock function with given fields: ctx, executionContext
func (_m *CacheableNode) IsCacheable(ctx context.Context, executionContext handler.NodeExecutionContext) (bool, bool, error) {
	ret := _m.Called(ctx, executionContext)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, handler.NodeExecutionContext) bool); ok {
		r0 = rf(ctx, executionContext)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(context.Context, handler.NodeExecutionContext) bool); ok {
		r1 = rf(ctx, executionContext)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, handler.NodeExecutionContext) error); ok {
		r2 = rf(ctx, executionContext)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type CacheableNode_Setup struct {
	*mock.Call
}

func (_m CacheableNode_Setup) Return(_a0 error) *CacheableNode_Setup {
	return &CacheableNode_Setup{Call: _m.Call.Return(_a0)}
}

func (_m *CacheableNode) OnSetup(ctx context.Context, setupContext handler.SetupContext) *CacheableNode_Setup {
	c_call := _m.On("Setup", ctx, setupContext)
	return &CacheableNode_Setup{Call: c_call}
}

func (_m *CacheableNode) OnSetupMatch(matchers ...interface{}) *CacheableNode_Setup {
	c_call := _m.On("Setup", matchers...)
	return &CacheableNode_Setup{Call: c_call}
}

// Setup provides a mock function with given fields: ctx, setupContext
func (_m *CacheableNode) Setup(ctx context.Context, setupContext handler.SetupContext) error {
	ret := _m.Called(ctx, setupContext)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, handler.SetupContext) error); ok {
		r0 = rf(ctx, setupContext)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
