// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/flyteorg/flytepropeller/pkg/controller/nodes/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NodeStateWriter is an autogenerated mock type for the NodeStateWriter type
type NodeStateWriter struct {
	mock.Mock
}

// ClearNodeStatus provides a mock function with given fields:
func (_m *NodeStateWriter) ClearNodeStatus() {
	_m.Called()
}

type NodeStateWriter_PutArrayNodeState struct {
	*mock.Call
}

func (_m NodeStateWriter_PutArrayNodeState) Return(_a0 error) *NodeStateWriter_PutArrayNodeState {
	return &NodeStateWriter_PutArrayNodeState{Call: _m.Call.Return(_a0)}
}

func (_m *NodeStateWriter) OnPutArrayNodeState(s interfaces.ArrayNodeState) *NodeStateWriter_PutArrayNodeState {
	c_call := _m.On("PutArrayNodeState", s)
	return &NodeStateWriter_PutArrayNodeState{Call: c_call}
}

func (_m *NodeStateWriter) OnPutArrayNodeStateMatch(matchers ...interface{}) *NodeStateWriter_PutArrayNodeState {
	c_call := _m.On("PutArrayNodeState", matchers...)
	return &NodeStateWriter_PutArrayNodeState{Call: c_call}
}

// PutArrayNodeState provides a mock function with given fields: s
func (_m *NodeStateWriter) PutArrayNodeState(s interfaces.ArrayNodeState) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.ArrayNodeState) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NodeStateWriter_PutBranchNode struct {
	*mock.Call
}

func (_m NodeStateWriter_PutBranchNode) Return(_a0 error) *NodeStateWriter_PutBranchNode {
	return &NodeStateWriter_PutBranchNode{Call: _m.Call.Return(_a0)}
}

func (_m *NodeStateWriter) OnPutBranchNode(s interfaces.BranchNodeState) *NodeStateWriter_PutBranchNode {
	c_call := _m.On("PutBranchNode", s)
	return &NodeStateWriter_PutBranchNode{Call: c_call}
}

func (_m *NodeStateWriter) OnPutBranchNodeMatch(matchers ...interface{}) *NodeStateWriter_PutBranchNode {
	c_call := _m.On("PutBranchNode", matchers...)
	return &NodeStateWriter_PutBranchNode{Call: c_call}
}

// PutBranchNode provides a mock function with given fields: s
func (_m *NodeStateWriter) PutBranchNode(s interfaces.BranchNodeState) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.BranchNodeState) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NodeStateWriter_PutDynamicNodeState struct {
	*mock.Call
}

func (_m NodeStateWriter_PutDynamicNodeState) Return(_a0 error) *NodeStateWriter_PutDynamicNodeState {
	return &NodeStateWriter_PutDynamicNodeState{Call: _m.Call.Return(_a0)}
}

func (_m *NodeStateWriter) OnPutDynamicNodeState(s interfaces.DynamicNodeState) *NodeStateWriter_PutDynamicNodeState {
	c_call := _m.On("PutDynamicNodeState", s)
	return &NodeStateWriter_PutDynamicNodeState{Call: c_call}
}

func (_m *NodeStateWriter) OnPutDynamicNodeStateMatch(matchers ...interface{}) *NodeStateWriter_PutDynamicNodeState {
	c_call := _m.On("PutDynamicNodeState", matchers...)
	return &NodeStateWriter_PutDynamicNodeState{Call: c_call}
}

// PutDynamicNodeState provides a mock function with given fields: s
func (_m *NodeStateWriter) PutDynamicNodeState(s interfaces.DynamicNodeState) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DynamicNodeState) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NodeStateWriter_PutGateNodeState struct {
	*mock.Call
}

func (_m NodeStateWriter_PutGateNodeState) Return(_a0 error) *NodeStateWriter_PutGateNodeState {
	return &NodeStateWriter_PutGateNodeState{Call: _m.Call.Return(_a0)}
}

func (_m *NodeStateWriter) OnPutGateNodeState(s interfaces.GateNodeState) *NodeStateWriter_PutGateNodeState {
	c_call := _m.On("PutGateNodeState", s)
	return &NodeStateWriter_PutGateNodeState{Call: c_call}
}

func (_m *NodeStateWriter) OnPutGateNodeStateMatch(matchers ...interface{}) *NodeStateWriter_PutGateNodeState {
	c_call := _m.On("PutGateNodeState", matchers...)
	return &NodeStateWriter_PutGateNodeState{Call: c_call}
}

// PutGateNodeState provides a mock function with given fields: s
func (_m *NodeStateWriter) PutGateNodeState(s interfaces.GateNodeState) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.GateNodeState) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NodeStateWriter_PutTaskNodeState struct {
	*mock.Call
}

func (_m NodeStateWriter_PutTaskNodeState) Return(_a0 error) *NodeStateWriter_PutTaskNodeState {
	return &NodeStateWriter_PutTaskNodeState{Call: _m.Call.Return(_a0)}
}

func (_m *NodeStateWriter) OnPutTaskNodeState(s interfaces.TaskNodeState) *NodeStateWriter_PutTaskNodeState {
	c_call := _m.On("PutTaskNodeState", s)
	return &NodeStateWriter_PutTaskNodeState{Call: c_call}
}

func (_m *NodeStateWriter) OnPutTaskNodeStateMatch(matchers ...interface{}) *NodeStateWriter_PutTaskNodeState {
	c_call := _m.On("PutTaskNodeState", matchers...)
	return &NodeStateWriter_PutTaskNodeState{Call: c_call}
}

// PutTaskNodeState provides a mock function with given fields: s
func (_m *NodeStateWriter) PutTaskNodeState(s interfaces.TaskNodeState) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.TaskNodeState) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NodeStateWriter_PutWorkflowNodeState struct {
	*mock.Call
}

func (_m NodeStateWriter_PutWorkflowNodeState) Return(_a0 error) *NodeStateWriter_PutWorkflowNodeState {
	return &NodeStateWriter_PutWorkflowNodeState{Call: _m.Call.Return(_a0)}
}

func (_m *NodeStateWriter) OnPutWorkflowNodeState(s interfaces.WorkflowNodeState) *NodeStateWriter_PutWorkflowNodeState {
	c_call := _m.On("PutWorkflowNodeState", s)
	return &NodeStateWriter_PutWorkflowNodeState{Call: c_call}
}

func (_m *NodeStateWriter) OnPutWorkflowNodeStateMatch(matchers ...interface{}) *NodeStateWriter_PutWorkflowNodeState {
	c_call := _m.On("PutWorkflowNodeState", matchers...)
	return &NodeStateWriter_PutWorkflowNodeState{Call: c_call}
}

// PutWorkflowNodeState provides a mock function with given fields: s
func (_m *NodeStateWriter) PutWorkflowNodeState(s interfaces.WorkflowNodeState) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.WorkflowNodeState) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
