// Code generated by informer-gen. DO NOT EDIT.

package resourceRequest

import (
	internalinterfaces2 "github.com/lyft/flytepropeller/k8s-scheduler/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha12 "github.com/lyft/flytepropeller/k8s-scheduler/pkg/client/informers/externalversions/resourceRequest/v1alpha1"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// V1alpha1 provides access to shared informers for resources in V1alpha1.
	V1alpha1() v1alpha12.Interface
}

type group struct {
	factory          internalinterfaces2.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces2.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces2.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces2.TweakListOptionsFunc) Interface {
	return &group{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// V1alpha1 returns a new v1alpha1.Interface.
func (g *group) V1alpha1() v1alpha12.Interface {
	return v1alpha12.New(g.factory, g.namespace, g.tweakListOptions)
}
