# This is default configuration file.
# Real configuration when running inside K8s (local or otherwise) lives in a ConfigMap
# The operator will replace "job" field with the correct job name
# ingressUrlFormat: "{{$jobCluster}}.xyz.net"
operator:
  useKubectlProxy: true
  containerNameFormat: "%s-unknown"
  metricsPrefix: "k8sschedulerextender"
  resyncPeriod: 10s
  proxyPort: 8001
logger:
  show-source: true
  level: 5
  formatter:
    type: text
