// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ResourceRequestListerExpansion allows custom methods to be added to
// ResourceRequestLister.
type ResourceRequestListerExpansion interface{}

// ResourceRequestNamespaceListerExpansion allows custom methods to be added to
// ResourceRequestNamespaceLister.
type ResourceRequestNamespaceListerExpansion interface{}
