// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/lyft/flytepropeller/k8s-scheduler/pkg/client/clientset/versioned/typed/resourcerequest/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFlyteV1alpha1 struct {
	*testing.Fake
}

func (c *FakeFlyteV1alpha1) ResourceRequests(namespace string) v1alpha1.ResourceRequestInterface {
	return &FakeResourceRequests{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFlyteV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
