// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces2 "github.com/lyft/flytepropeller/k8s-scheduler/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ResourceRequests returns a ResourceRequestInformer.
	ResourceRequests() ResourceRequestInformer
}

type version struct {
	factory          internalinterfaces2.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces2.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces2.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces2.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ResourceRequests returns a ResourceRequestInformer.
func (v *version) ResourceRequests() ResourceRequestInformer {
	return &resourceRequestInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
