// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"github.com/lyft/flytepropeller/k8s-scheduler/pkg/apis/resourceRequest/v1alpha1"
	versioned2 "github.com/lyft/flytepropeller/k8s-scheduler/pkg/client/clientset/versioned"
	internalinterfaces2 "github.com/lyft/flytepropeller/k8s-scheduler/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha12 "github.com/lyft/flytepropeller/k8s-scheduler/pkg/client/listers/resourcerequest/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ResourceRequestInformer provides access to a shared informer and lister for
// ResourceRequests.
type ResourceRequestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha12.ResourceRequestLister
}

type resourceRequestInformer struct {
	factory          internalinterfaces2.SharedInformerFactory
	tweakListOptions internalinterfaces2.TweakListOptionsFunc
	namespace        string
}

// NewResourceRequestInformer constructs a new informer for ResourceRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewResourceRequestInformer(client versioned2.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredResourceRequestInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredResourceRequestInformer constructs a new informer for ResourceRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredResourceRequestInformer(client versioned2.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces2.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FlyteV1alpha1().ResourceRequests(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FlyteV1alpha1().ResourceRequests(namespace).Watch(context.TODO(), options)
			},
		},
		&v1alpha1.ResourceRequest{},
		resyncPeriod,
		indexers,
	)
}

func (f *resourceRequestInformer) defaultInformer(client versioned2.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredResourceRequestInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *resourceRequestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&v1alpha1.ResourceRequest{}, f.defaultInformer)
}

func (f *resourceRequestInformer) Lister() v1alpha12.ResourceRequestLister {
	return v1alpha12.NewResourceRequestLister(f.Informer().GetIndexer())
}
