// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/flyteorg/flyteidl/gen/pb-go/flyteidl/event"

	mock "github.com/stretchr/testify/mock"
)

// WorkflowEventRecorder is an autogenerated mock type for the WorkflowEventRecorder type
type WorkflowEventRecorder struct {
	mock.Mock
}

type WorkflowEventRecorder_RecordWorkflowEvent struct {
	*mock.Call
}

func (_m WorkflowEventRecorder_RecordWorkflowEvent) Return(_a0 error) *WorkflowEventRecorder_RecordWorkflowEvent {
	return &WorkflowEventRecorder_RecordWorkflowEvent{Call: _m.Call.Return(_a0)}
}

func (_m *WorkflowEventRecorder) OnRecordWorkflowEvent(ctx context.Context, _a1 *event.WorkflowExecutionEvent, outputPolicy string) *WorkflowEventRecorder_RecordWorkflowEvent {
	c := _m.On("RecordWorkflowEvent", ctx, _a1, outputPolicy)
	return &WorkflowEventRecorder_RecordWorkflowEvent{Call: c}
}

func (_m *WorkflowEventRecorder) OnRecordWorkflowEventMatch(matchers ...interface{}) *WorkflowEventRecorder_RecordWorkflowEvent {
	c := _m.On("RecordWorkflowEvent", matchers...)
	return &WorkflowEventRecorder_RecordWorkflowEvent{Call: c}
}

// RecordWorkflowEvent provides a mock function with given fields: ctx, _a1, outputPolicy
func (_m *WorkflowEventRecorder) RecordWorkflowEvent(ctx context.Context, _a1 *event.WorkflowExecutionEvent, outputPolicy string) error {
	ret := _m.Called(ctx, _a1, outputPolicy)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *event.WorkflowExecutionEvent, string) error); ok {
		r0 = rf(ctx, _a1, outputPolicy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
