// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/flyteorg/flytestdlib/storage"

	v1alpha1 "github.com/flyteorg/flytepropeller/pkg/apis/flyteworkflow/v1alpha1"
)

// CRDOffloadStore is an autogenerated mock type for the CRDOffloadStore type
type CRDOffloadStore struct {
	mock.Mock
}

type CRDOffloadStore_Get struct {
	*mock.Call
}

func (_m CRDOffloadStore_Get) Return(_a0 *v1alpha1.StaticWorkflowData, _a1 error) *CRDOffloadStore_Get {
	return &CRDOffloadStore_Get{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *CRDOffloadStore) OnGet(ctx context.Context, dataReference storage.DataReference) *CRDOffloadStore_Get {
	c_call := _m.On("Get", ctx, dataReference)
	return &CRDOffloadStore_Get{Call: c_call}
}

func (_m *CRDOffloadStore) OnGetMatch(matchers ...interface{}) *CRDOffloadStore_Get {
	c_call := _m.On("Get", matchers...)
	return &CRDOffloadStore_Get{Call: c_call}
}

// Get provides a mock function with given fields: ctx, dataReference
func (_m *CRDOffloadStore) Get(ctx context.Context, dataReference storage.DataReference) (*v1alpha1.StaticWorkflowData, error) {
	ret := _m.Called(ctx, dataReference)

	var r0 *v1alpha1.StaticWorkflowData
	if rf, ok := ret.Get(0).(func(context.Context, storage.DataReference) *v1alpha1.StaticWorkflowData); ok {
		r0 = rf(ctx, dataReference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.StaticWorkflowData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, storage.DataReference) error); ok {
		r1 = rf(ctx, dataReference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type CRDOffloadStore_Remove struct {
	*mock.Call
}

func (_m CRDOffloadStore_Remove) Return(_a0 error) *CRDOffloadStore_Remove {
	return &CRDOffloadStore_Remove{Call: _m.Call.Return(_a0)}
}

func (_m *CRDOffloadStore) OnRemove(ctx context.Context, dataReference storage.DataReference) *CRDOffloadStore_Remove {
	c_call := _m.On("Remove", ctx, dataReference)
	return &CRDOffloadStore_Remove{Call: c_call}
}

func (_m *CRDOffloadStore) OnRemoveMatch(matchers ...interface{}) *CRDOffloadStore_Remove {
	c_call := _m.On("Remove", matchers...)
	return &CRDOffloadStore_Remove{Call: c_call}
}

// Remove provides a mock function with given fields: ctx, dataReference
func (_m *CRDOffloadStore) Remove(ctx context.Context, dataReference storage.DataReference) error {
	ret := _m.Called(ctx, dataReference)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.DataReference) error); ok {
		r0 = rf(ctx, dataReference)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
