// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import handler "github.com/lyft/flytepropeller/pkg/controller/nodes/handler"
import mock "github.com/stretchr/testify/mock"

import v1alpha1 "github.com/lyft/flytepropeller/pkg/apis/flyteworkflow/v1alpha1"

// HandlerFactory is an autogenerated mock type for the HandlerFactory type
type HandlerFactory struct {
	mock.Mock
}

// GetHandler provides a mock function with given fields: kind
func (_m *HandlerFactory) GetHandler(kind v1alpha1.NodeKind) (handler.Node, error) {
	ret := _m.Called(kind)

	var r0 handler.Node
	if rf, ok := ret.Get(0).(func(v1alpha1.NodeKind) handler.Node); ok {
		r0 = rf(kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(handler.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(v1alpha1.NodeKind) error); ok {
		r1 = rf(kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Setup provides a mock function with given fields: ctx, setup
func (_m *HandlerFactory) Setup(ctx context.Context, setup handler.SetupContext) error {
	ret := _m.Called(ctx, setup)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, handler.SetupContext) error); ok {
		r0 = rf(ctx, setup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
