// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// stateCodec is an autogenerated mock type for the stateCodec type
type stateCodec struct {
	mock.Mock
}

// Decode provides a mock function with given fields: _a0, _a1
func (_m *stateCodec) Decode(_a0 io.Reader, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Encode provides a mock function with given fields: _a0, _a1
func (_m *stateCodec) Encode(_a0 interface{}, _a1 io.Writer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, io.Writer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
