name: Flyteadmin Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    uses: flyteorg/flytetools/.github/workflows/lint.yml@reuseable

  tests:
    name: Unit Tests
    uses: flyteorg/flytetools/.github/workflows/tests.yml@reuseable

  docker-build:
    name: Docker Build Images
    uses: flyteorg/flytetools/.github/workflows/docker_build.yml@reuseable

  endtoend:
    name: End2End Test
    needs: [docker-build]
    uses: flyteorg/flytetools/.github/workflows/end2end.yml@reuseable

  integration:
    name: Integration Test
    needs: [docker-build]
    uses: flyteorg/flytetools/.github/workflows/integration.yml@reuseable

  generate:
    name: Check Go Gennerate
    uses: flyteorg/flytetools/.github/workflows/go_generate.yml@reuseable

  bump_version:
    name: Bump Version
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ endtoend,  integration, lint, tests ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/bump_version.yml@reuseable
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  goreleaser:
    name: Goreleaser
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ bump_version ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/goreleaser.yml@reuseable
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  push_docker_image:
    name: Build & Push Flyteadmin Image
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ bump_version ]
    uses: flyteorg/flytetools/.github/workflows/publish.yml@reuseable
    with:
      version: ${{ needs.bump_version.outputs.version }}
      dockerfile: Dockerfile
      push: true
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}
